// File: src/modules/graph/graphify-bridge.ts
/**
 * Graphify Bridge — In-memory loader and query interface for `graphify-out/graph.json`
 *
 * Graphify (https://github.com/safishamsi/graphify) extracts a tree-sitter knowledge
 * graph of the codebase to `graphify-out/graph.json`. This module reads that file at
 * first use, caches it in memory, and exposes a substring query API used by the chat
 * service to enrich the LLM system prompt with relevant code-entity context.
 *
 * Graceful degradation (FR-038):
 *   - missing file        → loadGraphifyIndex() returns null, queries return []
 *   - malformed JSON      → loadGraphifyIndex() returns null, queries return []
 *   - empty/null query    → returns []
 *
 * (Why a JSON-file bridge instead of an MCP server: the chat service runs in the same
 *  Node.js process as the Next.js server; reading a file is zero-friction, has no IPC
 *  overhead, and works identically in CI without a Python runtime.)
 */

import fs from 'node:fs';
import path from 'node:path';
import { logger } from '@/modules/shared/logger';

// One Graphify graph node — matches the on-disk JSON shape produced by `graphify update`
export interface GraphifyNode {
  /** Display label (e.g. "RootLayout()" or "page.tsx") */
  label: string;
  /** "code" | "doc" | "image" | "video" | … — Graphify's source classification */
  file_type: string;
  /** Absolute path to the source file Graphify extracted this node from */
  source_file: string;
  /** Source location string (e.g. "L22") — line where the symbol is defined */
  source_location: string;
  /** Stable ID generated by Graphify (slugified path or symbol) */
  id: string;
  /** Community ID from Leiden clustering — same number = related concern */
  community: number;
  /** Lowercased normalised label, used for substring matching */
  norm_label: string;
}

// On-disk graph shape — Graphify writes a NetworkX node-link export
interface GraphifyGraph {
  directed: boolean;
  multigraph: boolean;
  graph: Record<string, unknown>;
  nodes: GraphifyNode[];
  edges?: Array<{ source: string; target: string }>;
}

// One match returned by queryGraphifyEntities — flattened for chat-service consumption
export interface GraphifyMatch {
  /** "RootLayout()" or "page.tsx" */
  label: string;
  /** Repo-relative path (e.g. "src/app/layout.tsx") — absolute paths are normalised away */
  filePath: string;
  /** "L22" — line number string from Graphify */
  location: string;
  /** Community cluster id (useful when grouping matches by concern) */
  community: number;
}

// In-process cache: load once, reuse for the lifetime of the Node process.
// Set to `null` after a failed load so retries do not repeatedly hit the filesystem.
let cachedGraph: GraphifyGraph | null | undefined = undefined;

/**
 * Resolve the on-disk path for `graphify-out/graph.json`. Defaults to repo root.
 * Override with the GRAPHIFY_OUT_DIR env var (used by tests to point at a fixture).
 */
function resolveGraphPath(): string {
  const dir = process.env.GRAPHIFY_OUT_DIR ?? path.join(process.cwd(), 'graphify-out');
  return path.join(dir, 'graph.json');
}

/**
 * Reads `graphify-out/graph.json` once and caches the parsed object.
 * Returns null on file-missing, parse-error, or shape-mismatch (graceful degradation).
 *
 * Exported for tests; the public surface is `queryGraphifyEntities`.
 */
export function loadGraphifyIndex(): GraphifyGraph | null {
  if (cachedGraph !== undefined) return cachedGraph;

  const graphPath = resolveGraphPath();
  try {
    if (!fs.existsSync(graphPath)) {
      // Common case during local dev when graphify hasn't been run yet — log once at debug level
      logger.debug?.('[graphify-bridge] graph.json not found, skipping enrichment', { graphPath });
      cachedGraph = null;
      return null;
    }
    const raw = fs.readFileSync(graphPath, 'utf-8');
    const parsed = JSON.parse(raw) as GraphifyGraph;
    if (!parsed || !Array.isArray(parsed.nodes)) {
      logger.warn('[graphify-bridge] graph.json missing nodes[] array', { graphPath });
      cachedGraph = null;
      return null;
    }
    cachedGraph = parsed;
    return parsed;
  } catch (err) {
    // Parse errors, permission errors, anything else — never throw to the caller
    logger.warn('[graphify-bridge] failed to load graph.json', { err: String(err), graphPath });
    cachedGraph = null;
    return null;
  }
}

/**
 * Reset the in-memory cache. Test-only — production code never needs to call this.
 */
export function resetGraphifyCache(): void {
  cachedGraph = undefined;
}

/**
 * Convert an absolute Windows/Unix path into a repo-relative path so the
 * chat enrichment string is portable across machines.
 * (Why: graph.json embeds absolute paths from the build host; we don't want to
 *  leak `C:\Users\ajith\…` into LLM prompts.)
 */
function toRepoRelative(absPath: string): string {
  const cwd = process.cwd().replace(/\\/g, '/');
  const norm = absPath.replace(/\\/g, '/');
  return norm.startsWith(cwd) ? norm.slice(cwd.length + 1) : norm;
}

/**
 * Substring-match `query` against the Graphify graph's normalised labels.
 * Returns up to `limit` matches sorted by label length (shorter = more specific).
 *
 * @param query  raw user query — case is ignored, empty/whitespace returns []
 * @param limit  max matches to return (default 5 — keeps prompt-size budget tight)
 */
export function queryGraphifyEntities(query: string, limit = 5): GraphifyMatch[] {
  if (!query || !query.trim()) return [];
  const graph = loadGraphifyIndex();
  if (!graph) return [];

  const needle = query.toLowerCase();
  const matches: GraphifyMatch[] = [];

  for (const node of graph.nodes) {
    if (node.file_type !== 'code') continue; // limit enrichment to code nodes
    if (node.norm_label.includes(needle) || needle.includes(node.norm_label)) {
      matches.push({
        label: node.label,
        filePath: toRepoRelative(node.source_file),
        location: node.source_location,
        community: node.community,
      });
    }
  }

  // Shorter labels first — they tend to be more specific symbols rather than
  // file-level nodes (e.g. "POST()" before "route.ts").
  matches.sort((a, b) => a.label.length - b.label.length);
  return matches.slice(0, limit);
}
